// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGG8yr7Ba0ArFnH1AEceSfKo02FEHV8s',
    appId: '1:891599789645:web:c6d7b0582b2e8fa845c604',
    messagingSenderId: '891599789645',
    projectId: 'finaladvanced1',
    authDomain: 'finaladvanced1.firebaseapp.com',
    storageBucket: 'finaladvanced1.appspot.com',
    measurementId: 'G-KG4M05ZX8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq-86qV8mF_rh-gvIFgp5b8LVAoZbQ2HM',
    appId: '1:891599789645:android:a5426403cc3a0ee945c604',
    messagingSenderId: '891599789645',
    projectId: 'finaladvanced1',
    storageBucket: 'finaladvanced1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOP5WLdEnxiQ1Q1T3fXNSqw9omXFyFYQY',
    appId: '1:891599789645:ios:dde69f105c4a2f9645c604',
    messagingSenderId: '891599789645',
    projectId: 'finaladvanced1',
    storageBucket: 'finaladvanced1.appspot.com',
    iosBundleId: 'com.example.finalAdvancedExam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOP5WLdEnxiQ1Q1T3fXNSqw9omXFyFYQY',
    appId: '1:891599789645:ios:dde69f105c4a2f9645c604',
    messagingSenderId: '891599789645',
    projectId: 'finaladvanced1',
    storageBucket: 'finaladvanced1.appspot.com',
    iosBundleId: 'com.example.finalAdvancedExam1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGG8yr7Ba0ArFnH1AEceSfKo02FEHV8s',
    appId: '1:891599789645:web:1164746ca0d9242245c604',
    messagingSenderId: '891599789645',
    projectId: 'finaladvanced1',
    authDomain: 'finaladvanced1.firebaseapp.com',
    storageBucket: 'finaladvanced1.appspot.com',
    measurementId: 'G-NDHLN3XSBZ',
  );
}
